//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_web_Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacion()
        {
            this.Puntocarga = new HashSet<Puntocarga>();
        }
    
        public string Rut { get; set; }
        public int Capacidad { get; set; }
        public int Region { get; set; }
        public string Direccion { get; set; }
        public System.DateTime Hora_inicio { get; set; }
        public System.DateTime Hora_cierre { get; set; }
    
        public virtual Region Region1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puntocarga> Puntocarga { get; set; }
    }
}
